/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    DeVote: {
      address:
        "0x605ca49b0059852babbfb4349212e13d3ada7b7a7f9255132f2aa3d654dc6b1",
      abi: [
        {
          type: "impl",
          name: "DeVoteImpl",
          interface_name: "contracts::DeVote::IDeVote",
        },
        {
          type: "struct",
          name: "contracts::DeVote::PersonPublic",
          members: [
            {
              name: "wallet_id",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "id_number",
              type: "core::felt252",
            },
            {
              name: "role",
              type: "core::felt252",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::DeVote::PersonProposalStruct",
          members: [
            {
              name: "proposal_id",
              type: "core::felt252",
            },
            {
              name: "role",
              type: "core::integer::u8",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::DeVote::ProposalVoteTypeStruct",
          members: [
            {
              name: "vote_type",
              type: "core::felt252",
            },
            {
              name: "count",
              type: "core::integer::u256",
            },
            {
              name: "is_active",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::DeVote::ProposalVoterStruct",
          members: [
            {
              name: "has_voted",
              type: "core::bool",
            },
            {
              name: "role",
              type: "core::integer::u8",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::DeVote::ProposalPublic",
          members: [
            {
              name: "id",
              type: "core::felt252",
            },
            {
              name: "name",
              type: "core::felt252",
            },
            {
              name: "state",
              type: "core::integer::u8",
            },
            {
              name: "total_voters",
              type: "core::integer::u256",
            },
            {
              name: "has_voted",
              type: "core::integer::u256",
            },
            {
              name: "type_votes",
              type: "core::array::Array::<contracts::DeVote::ProposalVoteTypeStruct>",
            },
            {
              name: "voter",
              type: "contracts::DeVote::ProposalVoterStruct",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::DeVote::IDeVote",
          items: [
            {
              type: "function",
              name: "create_new_person",
              inputs: [
                {
                  name: "id_number",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "change_person_rol",
              inputs: [
                {
                  name: "wallet_id",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "new_rol",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_person",
              inputs: [],
              outputs: [
                {
                  type: "contracts::DeVote::PersonPublic",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_person_rol",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_person_id_number",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_person_proposals",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<contracts::DeVote::PersonProposalStruct>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "create_proposal",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "name",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_proposal",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "contracts::DeVote::ProposalPublic",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "add_voter",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "voter_id",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "modify_voters",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "wallet_id",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "role",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "remove_voters",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "wallet_id",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "add_vote_type",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "vote_type",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "remove_vote_type",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "vote_type",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_vote_types",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<contracts::DeVote::ProposalVoteTypeStruct>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "start_votation",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "vote",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
                {
                  name: "vote_type",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "end_votation",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "view_votation",
              inputs: [
                {
                  name: "proposal_id",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<contracts::DeVote::ProposalVoteTypeStruct>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::DeVote::DeVote::PersonAdded",
          kind: "struct",
          members: [
            {
              name: "wallet_id",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "id_number",
              type: "core::felt252",
              kind: "key",
            },
            {
              name: "role",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DeVote::DeVote::PersonUpdated",
          kind: "struct",
          members: [
            {
              name: "wallet_id_signer",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "wallet_id",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "role",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DeVote::DeVote::UnauthorizeEvent",
          kind: "struct",
          members: [
            {
              name: "function_name",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "type_error",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "wallet_id",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DeVote::DeVote::Event",
          kind: "enum",
          variants: [
            {
              name: "PersonAdded",
              type: "contracts::DeVote::DeVote::PersonAdded",
              kind: "nested",
            },
            {
              name: "PersonUpdated",
              type: "contracts::DeVote::DeVote::PersonUpdated",
              kind: "nested",
            },
            {
              name: "UnauthorizeEvent",
              type: "contracts::DeVote::DeVote::UnauthorizeEvent",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x305c079245ec1cb7fe7fcde9f0e0968515b4df5da52c814c87c77ffda86f31d",
    },
  },
} as const;

export default deployedContracts;
